apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gyo8g3y64-java-quarkus
  janus-idp.io/tekton: gyo8g3y64-java-quarkus
  backstage.io/kubernetes-id: gyo8g3y64-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: gyo8g3y64-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
